version: '3.7'
services:
    # Database
    db:
        image: mongo
        container_name: db
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}

    # NodeJS App
    app:
        build: .
        volumes:
            - ./:/usr/src/app
        links:
            - db
